# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chatroom_pb2 as chatroom__pb2


class ChatRoomStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/ChatRoom/register',
        request_serializer=chatroom__pb2.User.SerializeToString,
        response_deserializer=chatroom__pb2.SimpleResponse.FromString,
        )
    self.login = channel.unary_unary(
        '/ChatRoom/login',
        request_serializer=chatroom__pb2.User.SerializeToString,
        response_deserializer=chatroom__pb2.LoginResponse.FromString,
        )
    self.addFriend = channel.unary_unary(
        '/ChatRoom/addFriend',
        request_serializer=chatroom__pb2.addFriendRequest.SerializeToString,
        response_deserializer=chatroom__pb2.SimpleResponse.FromString,
        )
    self.getNewFriend = channel.unary_stream(
        '/ChatRoom/getNewFriend',
        request_serializer=chatroom__pb2.getNewFriendRequest.SerializeToString,
        response_deserializer=chatroom__pb2.Friend.FromString,
        )
    self.acceptNewFriend = channel.unary_unary(
        '/ChatRoom/acceptNewFriend',
        request_serializer=chatroom__pb2.acceptNewFriendRequest.SerializeToString,
        response_deserializer=chatroom__pb2.SimpleResponse.FromString,
        )
    self.listFriends = channel.unary_unary(
        '/ChatRoom/listFriends',
        request_serializer=chatroom__pb2.listFriendsRequest.SerializeToString,
        response_deserializer=chatroom__pb2.listFriendsResponse.FromString,
        )
    self.sendMessage = channel.unary_unary(
        '/ChatRoom/sendMessage',
        request_serializer=chatroom__pb2.sendMessageRequest.SerializeToString,
        response_deserializer=chatroom__pb2.SimpleResponse.FromString,
        )


class ChatRoomServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addFriend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getNewFriend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def acceptNewFriend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listFriends(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatRoomServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=chatroom__pb2.User.FromString,
          response_serializer=chatroom__pb2.SimpleResponse.SerializeToString,
      ),
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=chatroom__pb2.User.FromString,
          response_serializer=chatroom__pb2.LoginResponse.SerializeToString,
      ),
      'addFriend': grpc.unary_unary_rpc_method_handler(
          servicer.addFriend,
          request_deserializer=chatroom__pb2.addFriendRequest.FromString,
          response_serializer=chatroom__pb2.SimpleResponse.SerializeToString,
      ),
      'getNewFriend': grpc.unary_stream_rpc_method_handler(
          servicer.getNewFriend,
          request_deserializer=chatroom__pb2.getNewFriendRequest.FromString,
          response_serializer=chatroom__pb2.Friend.SerializeToString,
      ),
      'acceptNewFriend': grpc.unary_unary_rpc_method_handler(
          servicer.acceptNewFriend,
          request_deserializer=chatroom__pb2.acceptNewFriendRequest.FromString,
          response_serializer=chatroom__pb2.SimpleResponse.SerializeToString,
      ),
      'listFriends': grpc.unary_unary_rpc_method_handler(
          servicer.listFriends,
          request_deserializer=chatroom__pb2.listFriendsRequest.FromString,
          response_serializer=chatroom__pb2.listFriendsResponse.SerializeToString,
      ),
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=chatroom__pb2.sendMessageRequest.FromString,
          response_serializer=chatroom__pb2.SimpleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChatRoom', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
