# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatroom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatroom.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63hatroom.proto\"*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x0eSimpleResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x15\n\x05state\x18\x02 \x01(\x0e\x32\x06.State\"5\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x15\n\x05state\x18\x02 \x01(\x0e\x32\x06.State\"\x16\n\x06\x46riend\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n\x10\x61\x64\x64\x46riendRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0e\n\x06\x66riend\x18\x03 \x01(\t\"1\n\x12listFriendsRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"&\n\x13listFriendsResponse\x12\x0f\n\x07\x66riends\x18\x01 \x03(\t\"E\n\x16\x61\x63\x63\x65ptNewFriendRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0e\n\x06\x66riend\x18\x03 \x01(\t\"@\n\x12sendMessageRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06\x66riend\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"2\n\x13getNewFriendRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"&\n\x14getNewFriendResponse\x12\x0e\n\x06\x66riend\x18\x01 \x01(\t*\x1e\n\x05State\x12\x08\n\x04\x46\x61il\x10\x00\x12\x0b\n\x07Success\x10\x01\x32\xea\x02\n\x08\x43hatRoom\x12$\n\x08register\x12\x05.User\x1a\x0f.SimpleResponse\"\x00\x12 \n\x05login\x12\x05.User\x1a\x0e.LoginResponse\"\x00\x12\x31\n\taddFriend\x12\x11.addFriendRequest\x1a\x0f.SimpleResponse\"\x00\x12\x31\n\x0cgetNewFriend\x12\x14.getNewFriendRequest\x1a\x07.Friend\"\x00\x30\x01\x12=\n\x0f\x61\x63\x63\x65ptNewFriend\x12\x17.acceptNewFriendRequest\x1a\x0f.SimpleResponse\"\x00\x12:\n\x0blistFriends\x12\x13.listFriendsRequest\x1a\x14.listFriendsResponse\"\x00\x12\x35\n\x0bsendMessage\x12\x13.sendMessageRequest\x1a\x0f.SimpleResponse\"\x00\x62\x06proto3')
)

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Fail', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Success', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=580,
  serialized_end=610,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
Fail = 0
Success = 1



_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=60,
)


_SIMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleResponse',
  full_name='SimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='SimpleResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='SimpleResponse.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=114,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='LoginResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='LoginResponse.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=169,
)


_FRIEND = _descriptor.Descriptor(
  name='Friend',
  full_name='Friend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Friend.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=193,
)


_ADDFRIENDREQUEST = _descriptor.Descriptor(
  name='addFriendRequest',
  full_name='addFriendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='addFriendRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='addFriendRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friend', full_name='addFriendRequest.friend', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=258,
)


_LISTFRIENDSREQUEST = _descriptor.Descriptor(
  name='listFriendsRequest',
  full_name='listFriendsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='listFriendsRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='listFriendsRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=309,
)


_LISTFRIENDSRESPONSE = _descriptor.Descriptor(
  name='listFriendsResponse',
  full_name='listFriendsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friends', full_name='listFriendsResponse.friends', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=349,
)


_ACCEPTNEWFRIENDREQUEST = _descriptor.Descriptor(
  name='acceptNewFriendRequest',
  full_name='acceptNewFriendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='acceptNewFriendRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='acceptNewFriendRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friend', full_name='acceptNewFriendRequest.friend', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=420,
)


_SENDMESSAGEREQUEST = _descriptor.Descriptor(
  name='sendMessageRequest',
  full_name='sendMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='sendMessageRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friend', full_name='sendMessageRequest.friend', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='sendMessageRequest.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=486,
)


_GETNEWFRIENDREQUEST = _descriptor.Descriptor(
  name='getNewFriendRequest',
  full_name='getNewFriendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='getNewFriendRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='getNewFriendRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=538,
)


_GETNEWFRIENDRESPONSE = _descriptor.Descriptor(
  name='getNewFriendResponse',
  full_name='getNewFriendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend', full_name='getNewFriendResponse.friend', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=578,
)

_SIMPLERESPONSE.fields_by_name['state'].enum_type = _STATE
_LOGINRESPONSE.fields_by_name['state'].enum_type = _STATE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['SimpleResponse'] = _SIMPLERESPONSE
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['Friend'] = _FRIEND
DESCRIPTOR.message_types_by_name['addFriendRequest'] = _ADDFRIENDREQUEST
DESCRIPTOR.message_types_by_name['listFriendsRequest'] = _LISTFRIENDSREQUEST
DESCRIPTOR.message_types_by_name['listFriendsResponse'] = _LISTFRIENDSRESPONSE
DESCRIPTOR.message_types_by_name['acceptNewFriendRequest'] = _ACCEPTNEWFRIENDREQUEST
DESCRIPTOR.message_types_by_name['sendMessageRequest'] = _SENDMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['getNewFriendRequest'] = _GETNEWFRIENDREQUEST
DESCRIPTOR.message_types_by_name['getNewFriendResponse'] = _GETNEWFRIENDRESPONSE
DESCRIPTOR.enum_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

SimpleResponse = _reflection.GeneratedProtocolMessageType('SimpleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLERESPONSE,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:SimpleResponse)
  })
_sym_db.RegisterMessage(SimpleResponse)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

Friend = _reflection.GeneratedProtocolMessageType('Friend', (_message.Message,), {
  'DESCRIPTOR' : _FRIEND,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:Friend)
  })
_sym_db.RegisterMessage(Friend)

addFriendRequest = _reflection.GeneratedProtocolMessageType('addFriendRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDFRIENDREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:addFriendRequest)
  })
_sym_db.RegisterMessage(addFriendRequest)

listFriendsRequest = _reflection.GeneratedProtocolMessageType('listFriendsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTFRIENDSREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:listFriendsRequest)
  })
_sym_db.RegisterMessage(listFriendsRequest)

listFriendsResponse = _reflection.GeneratedProtocolMessageType('listFriendsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTFRIENDSRESPONSE,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:listFriendsResponse)
  })
_sym_db.RegisterMessage(listFriendsResponse)

acceptNewFriendRequest = _reflection.GeneratedProtocolMessageType('acceptNewFriendRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTNEWFRIENDREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:acceptNewFriendRequest)
  })
_sym_db.RegisterMessage(acceptNewFriendRequest)

sendMessageRequest = _reflection.GeneratedProtocolMessageType('sendMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGEREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:sendMessageRequest)
  })
_sym_db.RegisterMessage(sendMessageRequest)

getNewFriendRequest = _reflection.GeneratedProtocolMessageType('getNewFriendRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETNEWFRIENDREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:getNewFriendRequest)
  })
_sym_db.RegisterMessage(getNewFriendRequest)

getNewFriendResponse = _reflection.GeneratedProtocolMessageType('getNewFriendResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETNEWFRIENDRESPONSE,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:getNewFriendResponse)
  })
_sym_db.RegisterMessage(getNewFriendResponse)



_CHATROOM = _descriptor.ServiceDescriptor(
  name='ChatRoom',
  full_name='ChatRoom',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=613,
  serialized_end=975,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='ChatRoom.register',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login',
    full_name='ChatRoom.login',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_LOGINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addFriend',
    full_name='ChatRoom.addFriend',
    index=2,
    containing_service=None,
    input_type=_ADDFRIENDREQUEST,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getNewFriend',
    full_name='ChatRoom.getNewFriend',
    index=3,
    containing_service=None,
    input_type=_GETNEWFRIENDREQUEST,
    output_type=_FRIEND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='acceptNewFriend',
    full_name='ChatRoom.acceptNewFriend',
    index=4,
    containing_service=None,
    input_type=_ACCEPTNEWFRIENDREQUEST,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listFriends',
    full_name='ChatRoom.listFriends',
    index=5,
    containing_service=None,
    input_type=_LISTFRIENDSREQUEST,
    output_type=_LISTFRIENDSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='ChatRoom.sendMessage',
    index=6,
    containing_service=None,
    input_type=_SENDMESSAGEREQUEST,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATROOM)

DESCRIPTOR.services_by_name['ChatRoom'] = _CHATROOM

# @@protoc_insertion_point(module_scope)
